name: build_files

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 拉取仓库源代码
      - name: Checkout the code
        uses: actions/checkout@v4.2.0
        
      # 构建
      - name: Build the files
        run: |
          sudo apt-get install libnfc-bin libnfc-dev libnfc-examples
          autoreconf -is
          ./configure
          make && sudo make install

      # 打包上传生成的 exe 到的网页端
      - name: Upload build files
        uses: actions/upload-artifact@v3.2.1-node20
        with:
          name: my-build-files
          path: ./*
